### ISSUE TITLE
Long-term Survey

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [swcarpentry/assessment#10]
This is a test version of SWC - Long-term-followup Survey 2015

https://www.surveymonkey.com/create/survey/preview?r=true&sm=H57qUiV6Bgv06Szlepvw8b4t0eqmlsA3FnOb6kChQ4Idxqt4R_2BFg1Y8mHGZadYGMS1JqOnyn8RMfJqbrpL_2BRBg_3D_3D

**Comment by bjoyce3** [comment]
I really like the questions in the long-term survey. All of the surveys have been really good, but this one asks a bunch of things I didn't consider to think about before. 

Question 6: Here are some extraordinary (but concrete) outcomes that we hope your attendance at a workshop could result in. For any that apply to you since completing the workshop, please estimate how much you think Software Carpentry workshops, community, and learning materials contributed.
To->
For any that apply to you, please estimate how much you think Software Carpentry workshops, community, and learning materials contributed.

Minor typo in question 6: "Wining a Nobel Prize, Fields Medal, or equivalent for you field"  -> "your field"

**Comment by JasonJWilliamsNY** [comment]
Typo fixed

**Comment by chendaniely** [comment]
:+1: should we add "computer science" to the question: "19. What is your domain of research/study?" or is that assumed under 'high performance computing'

text box for 'other' gender?

**Comment by JasonJWilliamsNY** [comment]
These are good ideas, reluctant to change since we haven't needed them on the previous surveys.

**Comment by FCTweedie** [comment]
Hi, I've been reading this over with a Digital Humanities eye. It reads well to me - I have a few suggestions that would reflect what I hope my workshop participants take out of the experience, but they may be too basic - I'm more of a Data Carpentry teacher as for a lot of my students it's their first taste of programming.
At Q 9, would it be worth having something like "I have changed the way I collect and manage my data" - this may be covered by "the way I conduct my research"
Perhaps something like "I have tried a new method of interrogating my data" as well?
At Q 10, can it be a 'research publication' or similar instead of a 'scientific publication'?
At Q 21, would it be appropriate to add something like "format data correctly in order to analyse it programmatically"? 
I'm aware that SWC skews very sciencey, but you could also break down Humanities to sub-categories Languages & Linguistics, Culture and Communication studies, Historical & Philosophical Studies if you wanted a but more granularity.

**Comment by gvwilson** [comment]
> I'm aware that SWC skews very sciencey, but you could also break down 
> Humanities to sub-categories Languages & Linguistics, Culture and 
> Communication studies, Historical & Philosophical Studies if you 
> wanted a but more granularity.
> 
> +1
