### ISSUE TITLE
Fall 2015 Assessment roll out

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [swcarpentry/assessment#7]
We have a final draft of a new-post workshop survey. We need members of the assessment list to comment and correct before releasing this at our fall workshops. The survey can be found here: https://az1.qualtrics.com/SE/?SID=SV_00TOGc6xZviXrIp&Preview=Survey&Q_CHL=preview&BrandID=qtrial2015az1

**Comment by raynamharris** [comment]
The survey looks good and didn't take long to complete (I was just going to look over it, but I was prompted to answer questions, so I just pretended to be a student).  The column prompts for the questions "After taking this workshop, which statement best reflects how you feel about learning more on the following subjects?" is slightly long but is not unreadable. 

My university's Teaching and Learning Center offers free consulting to evaluate assessment. Maybe your there is a similar service at your institution....

**Comment by gvwilson** [comment]
I went through and answered the questions - while I want all the information, I think it needs to be shortened.  There are some ugly bits of formatting (which is minor):
![screen shot 2015-09-24 at 1 48 54 pm](https://cloud.githubusercontent.com/assets/911566/10073800/55c53db8-62c3-11e5-976c-2eb6b9a1d0c3.png)

but then this question took waaaaay too long to puzzle through:

![screen shot 2015-09-24 at 1 49 20 pm](https://cloud.githubusercontent.com/assets/911566/10073804/60a24a00-62c3-11e5-8d16-6eecd04a758d.png)

I like having the demographic questions at the end (so as to reduce the risk of stereotype threat).

**Comment by rgaiacs** [comment]
@JasonJWilliamsNY
1. The survey has
   
   > Please select how you rate the helpers (as a team) 
   > - You could get clear answers to your questions from the helpers
   > - The helpers were considerate
   > - The instructors were effective
   > - The instructors were enthusiastic
   
   You forgot to replace **instructors** with **helpers** when copy the questions. =)
2. For
   
   > After taking this workshop, which statement best reflects how you feel about learning more on the following subjects? 
   
   Can we replace the options with a slider where 0 is **not covered**, 1 is **not interested** and 10 is **very interested**? And we could add a text box if someone want to write their reasons.
3. Can we replace
   
   > I want to write my own function that can take in a series of values and calculate a mean
   
   with
   
   > I **can** write my own function that can take in a series of values and calculate a mean

**Comment by raynamharris** [comment]
Today, Jason and I met with two consultants to get feedback on the post-workshop survey. Below are detailed suggestions for improving 6 of the questions. All the others were excellent as is. 
1.  Change “I learned valuable skills” to “I learned skills that I can use in my research” because valuable is too vague and subjective. 
2.  “The instructors/helpers were effective” is vague. Maybe add an “(e.g. knowledgeable, good communicators)” or make multiple specific questions.
3.   A few suggestions/options for improving the questions “Before the workshop, did you feel any of the following topics were intimidating?
   a.  Change to a sliding scale response to allow finer resolution between intimidating and not intimidating.
   b.  Change the response to a Likert scale and rephrase the question to something like “For each topic, how well do you identify with the statement ‘Before the workshop, this topic was very intimidating.’” Or, you could use a “describes my feelings” scale or agree-disagree scale.
   c.  Also, students may not be able to accurately self-report on pre-workshop attitude after taking the workshop. This question could be move to pre-assessment survey.
4.  A few suggestions for “After taking this workshop, which statement best reflects how you feel about learning more on the following subjects?”
   a.  Change questions to “After taking the workshop, how interested are in you in learning more about the following topics
   b.  New responses could be something like i) uninterested, not relevant ii) uninterested, already know enough iii) slightly uninterested iv) neither uninterested nor  interested v) slightly interested vi) interested 
5.  For second skills questions, we might be able to get at BOTH 1) what was covered in the workshop AND 2) what skills were gained by the student using the side-by-side question format. For example:
   a.  The question would be: “For the following tasks, please rate the quality of instruction and how confident you are in your ability to perform the task
   b.  Scale for quality of instruction subset: poor-excellent  or above-below average
   c.  Scale for task performance subset: good chance - no chance or easy – difficult
   d.  See two possible examples in the attached image below
6.  Change “sex” to “gender” for demographic questions
7.  Smiley face question about having fun is awesome!!

![sidebyside](https://cloud.githubusercontent.com/assets/7544197/10182958/05306478-66f0-11e5-9028-e28c78a6c8b1.png)

**Comment by gvwilson** [comment]
Thanks for this, Rayna - can you please turn it into a blog post for 
SWC?  I think that showing people the questionnaire _and_ the 
improvements will help a lot of our instructors understand how to do 
this kind of assessment, which would be pretty useful.

Thanks,
Greg

On 2015-09-30 3:21 AM, Rayna M Harris wrote:

> Today, Jason and I met with two consultants to get feedback on the 
> post-workshop survey. Below are detailed suggestions for improving 6 
> of the questions. All the others were excellent as is.
> 
> 1.
> 
> ```
> Change “I learned valuable skills” to “I learned skills that I can
> use in my research” because valuable is too vague and subjective.
> ```
> 
> 2.
> 
> ```
> “The instructors/helpers were effective” is vague. Maybe add an
> “(e.g. knowledgeable, good communicators)” or make multiple
> specific questions.
> ```
> 
> 3.
> 
> ```
> A few suggestions/options for improving the questions “Before the
> workshop, did you feel any of the following topics were intimidating?
> a. Change to a sliding scale response to allow finer resolution
> between intimidating and not intimidating.
> b. Change the response to a Likert scale and rephrase the question
> to something like “For each topic, how well do you identify with
> the statement ‘Before the workshop, this topic was very
> intimidating.’” Or, you could use a “describes my feelings” scale
> or agree-disagree scale.
> c. Also, students may not be able to accurately self-report on
> pre-workshop attitude after taking the workshop. This question
> could be move to pre-assessment survey.
> ```
> 
> 4.
> 
> ```
> A few suggestions for “After taking this workshop, which statement
> best reflects how you feel about learning more on the following
> subjects?”
> a. Change questions to “After taking the workshop, how interested
> are in you in learning more about the following topics
> b. New responses could be something like i) uninterested, not
> relevant ii) uninterested, already know enough iii) slightly
> uninterested iv) neither uninterested nor interested v) slightly
> interested vi) interested
> ```
> 
> 5.
> 
> ```
> For second skills questions, we might be able to get at BOTH 1)
> what was covered in the workshop AND 2) what skills were gained by
> the student using the side-by-side question format. For example:
> a. The question would be: “For the following tasks, please rate
> the quality of instruction and how confident you are in your
> ability to perform the task
> b. Scale for quality of instruction subset: poor-excellent or
> above-below average
> c. Scale for task performance subset: good chance - no chance or
> easy – difficult
> d. See two possible examples in the attached image below
> ```
> 
> 6.
> 
> ```
> Change “sex” to “gender” for demographic questions
> ```
> 
> 7.
> 
> ```
> Smiley face question about having fun is awesome!!
> ```
> 
> sidebyside 
> https://cloud.githubusercontent.com/assets/7544197/10182958/05306478-66f0-11e5-9028-e28c78a6c8b1.png
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/swcarpentry/assessment/issues/7#issuecomment-144261448.

## 

Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by raynamharris** [comment]
Of course.  I'll start working on a blog post later today.  I think that
the comments and suggestions for improving assessment will be widely
applicable and relevant to the community.

On Wed, Sep 30, 2015 at 4:04 AM, Greg Wilson notifications@github.com
wrote:

> Thanks for this, Rayna - can you please turn it into a blog post for
> SWC? I think that showing people the questionnaire _and_ the
> improvements will help a lot of our instructors understand how to do
> this kind of assessment, which would be pretty useful.
> 
> Thanks,
> Greg
> 
> On 2015-09-30 3:21 AM, Rayna M Harris wrote:
> 
> > Today, Jason and I met with two consultants to get feedback on the
> > post-workshop survey. Below are detailed suggestions for improving 6
> > of the questions. All the others were excellent as is.
> > 
> > 1.
> > 
> > Change “I learned valuable skills” to “I learned skills that I can
> > use in my research” because valuable is too vague and subjective.
> > 
> > 2.
> > 
> > “The instructors/helpers were effective” is vague. Maybe add an
> > “(e.g. knowledgeable, good communicators)” or make multiple
> > specific questions.
> > 
> > 3.
> > 
> > A few suggestions/options for improving the questions “Before the
> > workshop, did you feel any of the following topics were intimidating?
> > a. Change to a sliding scale response to allow finer resolution
> > between intimidating and not intimidating.
> > b. Change the response to a Likert scale and rephrase the question
> > to something like “For each topic, how well do you identify with
> > the statement ‘Before the workshop, this topic was very
> > intimidating.’” Or, you could use a “describes my feelings” scale
> > or agree-disagree scale.
> > c. Also, students may not be able to accurately self-report on
> > pre-workshop attitude after taking the workshop. This question
> > could be move to pre-assessment survey.
> > 
> > 4.
> > 
> > A few suggestions for “After taking this workshop, which statement
> > best reflects how you feel about learning more on the following
> > subjects?”
> > a. Change questions to “After taking the workshop, how interested
> > are in you in learning more about the following topics
> > b. New responses could be something like i) uninterested, not
> > relevant ii) uninterested, already know enough iii) slightly
> > uninterested iv) neither uninterested nor interested v) slightly
> > interested vi) interested
> > 
> > 5.
> > 
> > For second skills questions, we might be able to get at BOTH 1)
> > what was covered in the workshop AND 2) what skills were gained by
> > the student using the side-by-side question format. For example:
> > a. The question would be: “For the following tasks, please rate
> > the quality of instruction and how confident you are in your
> > ability to perform the task
> > b. Scale for quality of instruction subset: poor-excellent or
> > above-below average
> > c. Scale for task performance subset: good chance - no chance or
> > easy – difficult
> > d. See two possible examples in the attached image below
> > 
> > 6.
> > 
> > Change “sex” to “gender” for demographic questions
> > 
> > 7.
> > 
> > Smiley face question about having fun is awesome!!
> > 
> > sidebyside
> > <
> > https://cloud.githubusercontent.com/assets/7544197/10182958/05306478-66f0-11e5-9028-e28c78a6c8b1.png
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/swcarpentry/assessment/issues/7#issuecomment-144261448
> > .
> 
> ## 
> 
> Dr. Greg Wilson | gvwilson@software-carpentry.org
> Software Carpentry | http://software-carpentry.org
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/swcarpentry/assessment/issues/7#issuecomment-144333259
> .

## 

Rayna M. Harris
Graduate Student, Hans Hofmann Lab
The University of Texas at Austin
raynamharris.github.io

**Comment by JasonJWilliamsNY** [comment]
Just an update to everyone - Rayna and I discussed the survey with some of the assessment folks at her institution. Right now, we are moving the Survey into Survey Monkey (which going to be an order of magnitude cheaper than Qualtrics given what we need). Up next, pre-survey.

**Comment by rgaiacs** [comment]
Based on https://pt.surveymonkey.com/create/survey/preview?r=true&sm=ySIDD9XyFd7AhG8X2dg4nRnnOvmbA5XNoExtfTkaua2YJZPkE5CfZRPCjTZwwxDK61_2Fv53FnwF7Oj2WcYPYSoA_3D_3D:
1. At "6. Please select how you perceived how the helpers performed as a team " the questions still have **instructors** instead of **helpers**.
2. Do we have slice? "18. What overall grade would you give this workshop?" and "19. How much fun did you have at the workshop?" will be better with one.
3. "20. How much fun did you have at the workshop?" is duplicated.

**Comment by gvwilson** [comment]
Question 6 is about helpers, but the actual prompts all say 'instructors'.

**Comment by gvwilson** [comment]
Question 10: should "wasn't covered" be an option? Surprising how many people think X wasn't covered when the instructors tell us it was :-)

**Comment by JasonJWilliamsNY** [comment]
Fixed Duplicated questions and helper question. For Q10 "Before the workshop tell us about your experience with these topics." I did not have a 'Wasn't covered' is this the question you meant Greg?

**Comment by gvwilson** [comment]
Yup.

**Comment by JasonJWilliamsNY** [comment]
I asked the question here because it is a chance to ask about prior knowledge even if we did not cover the topic. We could ask this on a pre-survey, but since those data will not be linked to an individual, this before question + the after questions may help us to gauge if participants think they had changes in knowledge or perception during the workshop.

**Comment by JasonJWilliamsNY** [comment]
I have really sharpened (I hope Q11-14); also added a US-only demographics page.

**Comment by bjoyce3** [comment]
Some suggestions: 
6. Please select how you perceived how the instructors performed as a team --> "Please select how the instructors performed as a team"
I don't think we have to ask how they perceived it, because by definition that's the only thing a survey taker can provide...Also it may be hard to provide feedback for all instructors if you have 4 in a workshop, and they were each very different. Is there a way for instructors to opt in to have individual responses in the survey? Speaking personally, I'd like to receive that kind of feedback (especially if it's negative) so I know what to work on in the future.

Question 7. Please select how you perceived how the helpers performed as a team --> "Please select how the helpers performed as a team"

**Comment by bjoyce3** [comment]
For questions 11-14 we should consider including the N/A option for responses for the sake of consistency and downstream data processing. Most workshops won't cover all of these topics obviously, and if there's not a N/A option that could cause confusion.

**Comment by bjoyce3** [comment]
Question 16: you may consider adding in the Medicine and Pharmacy field as most of those researchers don't consider themselves Life Scientists (either genetics or organism/systems).

**Comment by JasonJWilliamsNY** [comment]
@bjoyce3 - Q6; Would 'felt' work? I wanted to emphasize that this was totally a personal opinion. Also, besides not knowing the names of the instructors, we decided to ask for a team rating to acknowledge that it is a team effort and the idea is that strengths and weaknesses will balance. We left the free-response essay in this section so that have a chance for respondents to give personalized feedback if they choose to.

**Comment by JasonJWilliamsNY** [comment]
@bjoyce3 for Q11,14 I have made the 'no opinion/no change' option to explicitly include N/A. Others already had N/A. Also the section has a tip where we say they need only answer portions of the question they feel apply. Do you think this is adequate?

**Comment by JasonJWilliamsNY** [comment]
@bjoyce3 - added medicine and/or pharmacy

**Comment by bjoyce3** [comment]
Cool on all accounts. "Felt" is plenty fine; I was more interested in just changing the structure of the sentence so that it wasn't redundant (and therefore a little hard to read).

**Comment by JasonJWilliamsNY** [comment]
Thanks for the feedback.
