### ISSUE TITLE
Software Carpentry Pre-workshop Survey

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [swcarpentry/assessment#9]
Hi Everyone, 

Preview the Survey Here; 
https://www.surveymonkey.com/create/survey/preview?r=true&sm=16wnNYRoEi2P3fwKZMLuYLvbImRjqbWn7MjeBqePiD54hm1Qqmnn2nJjrLhl1_2FBZ3DLZSM01zZnC7tJS5NyYHw_3D_3D          

Comments by Oct 31st if possible

**Comment by raynamharris** [comment]
Question 2: Who will update this each week or so?  Will updating it each week have any unwanted negative side effects? It might be worth testing how the report looks after this question gets changed a handful of times after the survey has been launched. 

Question10-13:  I don't think the Tip is necessary for a fe reasons.  A) learners may not know what topics will be covered. B) Even if the topic won't be covered, it could still be good for the broader SWC mission to collect info on their pre-workshop attitude. 

Question 10 & 11.  Why do we have to answer the intimidation question twice?

**Comment by bjoyce3** [comment]
For Questions 6 & 7 I'm echoing raynamharris's comments about answering the perception questions twice. Maybe move those to a separate question, or for question #7 change it from perception => how often do you think you would use this in your research (which helps reinforce the relevance to research question). 

I'm a little confused about how students would not know the topics in the class. I thought the first thing that's done for any workshop is creating the SWC main page that includes a schedule.

**Comment by JasonJWilliamsNY** [comment]
@raynamharris Q2: The SWC admin will update this. They can update this weeks in advance, and if some how a workshop is missing, and other category will allow the user to fill in details. 
I think you mean Q12-15 on 'Your attitudes...' page - if you selected that this was not your first workshop there is another page. As for the Tip; theoretically everyone should know that these are covered when they read the description. I have reworded the tip to be: "If you are sure a topic will not covered at your workshop, simply leave that portion of the question blank or select the N/A options in the drop-down menus" . If this is still confusing then I could ditch the tip is no alternative is suggested. Duplicate relevance is removed.

**Comment by maneesha** [comment]
​Here are some of my comments.  I think the survey may been edited while I
was putting together these comments because some notes no longer apply.
Let me know if you have any questions about any of my comments.

-Maneesha

# 

In intro text: Is responding by email an option?  (​"​If you respond via
email, your IP address will be registered​"​)

Question 3 should be required.

Question 3 - "as a learner" seems redundant, unless we think someone would
attend as a learner _after_ attending as a helper or instructor -- or are
there other ways they might attend?

## If Branch yes for question 3:

Question 8

Change to:
1. How did you hear about Software Carpentry? Please select as many as
   apply.
   (as is it's not a question)
2. There may have been reasons that would discourage you from attending the
   workshop before you decided to attend.
   If you experienced any strong concerns can you let us know what they were?
   Did we address these concerns, or were there ways we could have addressed
   them?

This phrasing is clunky.
 Maybe something like:

If you experienced any strong concerns about attending this workshop, can
you let us know what they were? Did we address these concerns, or were
there ways we could have addressed them?

We would like to know more about how you felt about the workshop topics
before and after the workshop.
Needs a period

Tip for questions 10-13:
Edit for grammar:
Tip: If you are not sure a topic will be covered at your workshop, simply
leave that portion of the question blank or select the N/A options in the
drop-down menus

Also:
Don't offer them the option to leave it blank - make them choose NA if
that's the case.  Otherwise there's no way to distinguish someone who
 skipped a question vs. thought it didn't apply.
1. Tell us about your experience with the following topics.

Needs a period or colon.

Question about being in US - is it supposed to branch?  Either answer leads
to race question which isn't relevant in the same way in other parts of
world.  If it does not branch then what's the point of the question? (if we
know what workshop the survey is for we know the answer to that question)

## If Branch no for question 3:
1. How long ago did you attend a Software Carpentry workshop?
   In the last 30 days
   Within the last 6 months
   Within the last Year

These options are inclusive of each other.  Rephrase to

In the last 30 days
1-5 months ago
6-12 months ago
1. Here are some reasons we think people might attend another Workshop;
   select all that apply

​change to

Why did you decide to attend another workshop? Select all that apply.
(As is it's not a question)

Tip for questions 6-9:
same comment as above

**Comment by JasonJWilliamsNY** [comment]
@maneesha 
- Intro text: 'email response' and a few other grammar issues may have to be fixed in all of these before we release.
-  Fixed Q3 required
-  How did you hear (fixed)
- Strong concerns (fixed)
- Fixed grammar points
- I have chosen not to require N/As because it saves the user time. Its not as nice for us, but should result in better completion/less frustration
- More grammar fixed
- US question logic fixed and required
- Time since hearing about SWC fixed, also made it 6 Mo or more
- Why attend - fixed

@maneesha Thanks for the helpful points - for grammar, feel free edit directly in the survey, or we can cover in our call Friday.

**Comment by raynamharris** [comment]
@JasonJWilliamsNY Cool.  Thanks for the clarification.

**Comment by davidedelvento** [comment]
Is this pre-survey for us of for the students?

From the feedback I've received by participants after hosting SWC and DC several times, many students do not have a clear idea of what they know and what they will be taught. We often have ended up with students that were expecting much more or much less than was offered. Some of these students have suggested a survey to tell them if they need to participate or not, but without questions like "current level of knowledge and intimidation of the Unix shell", because they say "I have no idea what my level of knowledge is, I'm a climate scientist who uses the shell, but I don't know if I know 1% of the shell or maybe 80% of it". They suggested instead questions like:

_You have a large number of text files in a directory, and would like to create a file which lists the SIZE of all the files that contain the word FOO in them. Do you know how to do it?_ Possible answers: _Everything easily, only some parts of the request but the rest I could probably figure out googling, only some parts of the request with no idea how to complete the rest, not at all._ (from such a question one knows if they know grep, output redirection, shell looping, and maybe even about their intimidation) 

Also, I'd suggest REDUCING the number of questions and making it a single page, maximum dual page. In my experience each additional page halves the number of respondents (of course having a huge page with a zillion of questions doesn't help either, the number of question per page must be reasonable, say around 10).

**Comment by JasonJWilliamsNY** [comment]
Thanks for the feedback.
